// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesProgrammer.Models;

#nullable disable

namespace TesProgrammer.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251015144751_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TesProgrammer.Models.DB.Dosen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KodeDosen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NamaDosen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TahunPensiun")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Dosens");
                });

            modelBuilder.Entity("TesProgrammer.Models.DB.DosenMatakuliah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DosenId")
                        .HasColumnType("int");

                    b.Property<int>("MataKuliahId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DosenId");

                    b.HasIndex("MataKuliahId");

                    b.ToTable("DosenMataKuliahs");
                });

            modelBuilder.Entity("TesProgrammer.Models.DB.Matakuliah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KodeMataKuliah")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NamaMataKuliah")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MataKuliahs");
                });

            modelBuilder.Entity("TesProgrammer.Models.DB.DosenMatakuliah", b =>
                {
                    b.HasOne("TesProgrammer.Models.DB.Dosen", "Dosen")
                        .WithMany("DosenMataKuliahs")
                        .HasForeignKey("DosenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesProgrammer.Models.DB.Matakuliah", "MataKuliah")
                        .WithMany()
                        .HasForeignKey("MataKuliahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dosen");

                    b.Navigation("MataKuliah");
                });

            modelBuilder.Entity("TesProgrammer.Models.DB.Dosen", b =>
                {
                    b.Navigation("DosenMataKuliahs");
                });
#pragma warning restore 612, 618
        }
    }
}
